// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC0vpWzrB2qtL6TloW-cc4jt3KabpKQ_0',
    appId: '1:795575695879:web:b6e931ed08e7a000b088a2',
    messagingSenderId: '795575695879',
    projectId: 'suiko-shop',
    authDomain: 'suiko-shop.firebaseapp.com',
    storageBucket: 'suiko-shop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpHVAif4to8p3HSPWN7x8jv2z09dmtcCY',
    appId: '1:795575695879:android:6f8d7a506d5492deb088a2',
    messagingSenderId: '795575695879',
    projectId: 'suiko-shop',
    storageBucket: 'suiko-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWGFH3pTiFSunj0iCH3ePXmXQ28T9M_1s',
    appId: '1:795575695879:ios:5ecc0e1d98bd9d4ab088a2',
    messagingSenderId: '795575695879',
    projectId: 'suiko-shop',
    storageBucket: 'suiko-shop.firebasestorage.app',
    iosBundleId: 'com.example.flutterApiGetxMatjer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWGFH3pTiFSunj0iCH3ePXmXQ28T9M_1s',
    appId: '1:795575695879:ios:5ecc0e1d98bd9d4ab088a2',
    messagingSenderId: '795575695879',
    projectId: 'suiko-shop',
    storageBucket: 'suiko-shop.firebasestorage.app',
    iosBundleId: 'com.example.flutterApiGetxMatjer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC0vpWzrB2qtL6TloW-cc4jt3KabpKQ_0',
    appId: '1:795575695879:web:d5af8e36dd677c41b088a2',
    messagingSenderId: '795575695879',
    projectId: 'suiko-shop',
    authDomain: 'suiko-shop.firebaseapp.com',
    storageBucket: 'suiko-shop.firebasestorage.app',
  );
}
